//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL
{
    public class CommonEntity
    {
        public virtual DateTime CreatedDate
        {
            get;
            set;
        }

        public virtual DateTime? LastUpdatedDate
        {
            get;
            set;
        }

        public int DaysCountInUmAlquraYear
        {
            get
            {
                return 354;
            }
        }

        public int DaysCountInGregYear
        {
            get
            {
                return 365;
            }
        }

        public decimal DaysCountInUmAlquraMonth
        {
            get
            {
                return 29.5M;
            }
        }

        public decimal DaysCountInGregMonth
        {
            get
            {
                return 30.5M;
            }
        }

        public EmployeesCodesBLL CreatedBy { get; internal set; }

        public EmployeesCodesBLL LastUpdatedBy { get; internal set; }

        public EmployeesCodesBLL LoginIdentity { internal get; set; }

        #region DataTable Server Side Prop
        public string Search { get; set; }
        public string Order { get; set; }
        public string OrderByColumnName { get; set; }
        public string OrderDir { get; set; }
        public int StartRec { get; set; }
        public int PageSize { get; set; }
        #endregion//DataTable  Server Side Prop
    }
}

