using HCMDAL;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL
{
    public class RanksCategoriesBLL : CommonEntity
    {
        public virtual int RankCategoryID
        {
            get;
            set;
        }

        public virtual string RankCategoryName
        {
            get;
            set;
        }

        public string RankCategoryNameEn { get; set; }

        public double RetirementPercentage { get; set; }

        public virtual IEnumerable<OrganizationsJobsBLL> OrganizationsJobsBLL
        {
            get;
            set;
        }

        public virtual List<RanksCategoriesBLL> GetRanksCategories()
        {
            List<RanksCategories> RanksCategoriesList = new RanksCategoriesDAL().GetRanksCategories();
            List<RanksCategoriesBLL> RanksCategoriesBLLList = new List<RanksCategoriesBLL>();
            if (RanksCategoriesList.Count > 0)
            {
                foreach (var item in RanksCategoriesList)
                {
                    RanksCategoriesBLLList.Add(new RanksCategoriesBLL()
                    {
                        RankCategoryID = item.RankCategoryID,
                        RankCategoryName = item.RankCategoryName
                    });
                }
            }

            return RanksCategoriesBLLList;
        }

        public RanksCategoriesBLL GetByRankCategoryID(int RankCategoryID)
        {
            return GetRanksCategories().SingleOrDefault(x => x.RankCategoryID.Equals(RankCategoryID));
        }

        internal RanksCategoriesBLL MapRanksCategories(RanksCategories item)
        {
            return item != null ?
                   new RanksCategoriesBLL()
                   {
                       RankCategoryID = item.RankCategoryID,
                       RankCategoryName = item.RankCategoryName,
                       RankCategoryNameEn = item.RankCategoryNameEn,
                       RetirementPercentage = item.RetirementPercentage.HasValue ? item.RetirementPercentage.Value : 0
                   }
                   : null;
        }

        public virtual int Add()
        {
            throw new System.NotImplementedException();
        }

        public virtual int Remove()
        {
            throw new System.NotImplementedException();
        }

        public virtual int Update()
        {
            throw new System.NotImplementedException();
        }

    }
}

