using HCMBLL.Enums;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace HCMBLL
{
    public class ExceptionalVacationsBLL : BaseVacationsBLL
    {
        public override VacationsTypesEnum VacationType
        {
            get
            {
                return VacationsTypesEnum.Exceptional;
            }
        }

        /// <summary>
        /// 1- Dated: First Release
        /// Rule :
        /// Employee gets 354 exceptional vacation every 5 years
        /// 2-
        /// Dated: 01-01-2020
        /// Rule :
        /// New limit for Contractual-Saudis and Expats is 21 Days exception leaves every year
        /// and for other employees 354 every five years
        /// </summary>
        public int LeaveDaysLimit
        {
            get
            {
                //EmployeesCareersHistoryBLL EmployeeCareerHistory = new EmployeesCareersHistoryBLL(). GetEmployeeCurrentJob(this.EmployeeCareerHistory.EmployeeCode.EmployeeCodeID);

                if (this.EmployeeCareerHistory.OrganizationJob.Rank.RankCategory.RankCategoryID == (int)RanksCategoriesEnum.ContractualSaudis ||
                    this.EmployeeCareerHistory.OrganizationJob.Rank.RankCategory.RankCategoryID == (int)RanksCategoriesEnum.ContractualExpats)
                {
                    return this.DaysCountInUmAlquraYear;
                }
                else
                {
                    return this.DaysCountInUmAlquraYear * 5;
                }
            }
        }

        public override Result Add()
        {
            try
            {
                Result result = null;

                #region Validation for vacation creation during probation period
                //EmployeesCareersHistoryBLL HiringRecord = new EmployeesCareersHistoryBLL().GetHiringRecordByEmployeeCodeID(this.EmployeeCareerHistory.EmployeeCode.EmployeeCodeID);
                //if (HiringRecord != null)
                //{
                //    // probation period = hiring date + 1 year
                //    DateTime ProbationEndDate = HiringRecord.ProbationEndDate; //Globals.Calendar.AddYearMonthDayInUmAlQuraDate(HiringRecord.JoinDate, 1, 0, 0);    //  HiringRecord.JoinDate.AddYears(1).AddDays(-10);
                //    if (ProbationEndDate > this.VacationStartDate)
                //    {
                //        result = new Result();
                //        result.Entity = HiringRecord;
                //        result.EnumType = typeof(VacationsValidationEnum);
                //        result.EnumMember = VacationsValidationEnum.RejectedBecauseOfDuringProbation.ToString();
                //        return result;
                //    }
                //}
                #endregion

                #region Validation for balanace
                result = IsBalanceValid();
                if (result != null)
                    return result;
                #endregion

                #region Validation for if employee has normal balance and he does not work as a teacher
                // check employee works as a teacher or not ... if he works as a teacher, he can get exceptional vacation even if he has normal vacation balance or not
                bool IsEmployeeWorksAsTeacher = new TeachersBLL().IsEmployeeWorksAsTeacher(this.EmployeeCareerHistory.EmployeeCode.EmployeeCodeID, this.VacationStartDate, this.VacationEndDate);
                if (IsEmployeeWorksAsTeacher == false)
                {
                    result = IsNormalVacationExistsAndConsumedMaxLimit();
                    if (result != null)
                        return result;
                }

                #endregion

                #region base validation
                result = base.Add();
                #endregion

                return result;
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public override Result Edit()
        {
            this.EmployeeCareerHistory = this.GetByVacationID(this.VacationID).EmployeeCareerHistory; // to get EmployeeCodeID
            Result result = new Result();

            #region Validation for vacation creation during probation period 
            // it was stoped by user
            //EmployeesCareersHistoryBLL HiringRecord = new EmployeesCareersHistoryBLL().GetHiringRecordByEmployeeCodeID(this.EmployeeCareerHistory.EmployeeCode.EmployeeCodeID);
            //if (HiringRecord != null)
            //{
            //    // probation period = hiring date + 1 year
            //    DateTime ProbationEndDate = HiringRecord.ProbationEndDate;//.JoinDate.AddYears(1).AddDays(-10);
            //    if (ProbationEndDate > this.VacationStartDate)
            //    {
            //        result = new Result();
            //        result.Entity = HiringRecord;
            //        result.EnumType = typeof(VacationsValidationEnum);
            //        result.EnumMember = VacationsValidationEnum.RejectedBecauseOfDuringProbation.ToString();
            //        return result;
            //    }
            //}
            #endregion

            #region Validation for balanace
            result = IsBalanceValid(this.VacationID);
            if (result != null)
                return result;

            result = IsNormalVacationExistsAndConsumedMaxLimit();
            if (result != null)
                return result;
            #endregion

            #region base validation
            result = base.Edit();

            #endregion

            return result;
        }

        public override Result Extend()
        {
            try
            {
                this.EmployeeCareerHistory = this.GetByVacationID(this.VacationID).EmployeeCareerHistory; // to get employee code id
                Result result = new Result();

                #region Validation for balanace                
                result = IsBalanceValid();
                if (result != null)
                    return result;

                result = IsNormalVacationExistsAndConsumedMaxLimit();
                if (result != null)
                    return result;
                #endregion

                #region base validation
                result = base.Extend();

                #endregion

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override Result Break()
        {
            try
            {
                Result result = base.Break();

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override Result Cancel()
        {
            try
            {
                Result result = base.Cancel();

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        internal override Result IsBalanceValid(int VacationID = 0)
        {
            Result result = null;

            List<VacationBalanceTable> VacationBalanceTable = GetBalanceTable(this.EmployeeCareerHistory.EmployeeCode.EmployeeCodeID, this.VacationStartDate, VacationID);

            if ((this.VacationConsumedBalance + this.VacationPeriod) > this.VacationBalance)
            {
                result = new Result();
                result.Entity = null;
                result.EnumType = typeof(VacationsValidationEnum);
                result.EnumMember = VacationsValidationEnum.RejectedBecauseOfNoBalance.ToString();
            }
            else
            {
                if (VacationBalanceTable.Count > 0)
                {
                    List<VacationBalanceTable> VacationBalanceTableFiltered = VacationBalanceTable
                                                                                    .Where(v => (v.StartDate <= this.VacationStartDate && v.EndDate >= this.VacationStartDate) &&
                                                                                          (v.StartDate <= this.VacationEndDate && v.EndDate >= this.VacationEndDate))
                                                                                    .ToList();

                    if (VacationBalanceTableFiltered.Count <= 0)
                    {
                        result = new Result();
                        result.Entity = null;
                        result.EnumType = typeof(VacationsValidationEnum);
                        result.EnumMember = VacationsValidationEnum.RejectedBecauseSickExceptionalVacationDatesOutOfRange.ToString();
                    }
                }
            }

            return result;
        }

        public List<VacationBalanceTable> GetBalanceTable(int EmployeeCodeID, DateTime? VacationStartDat, int VacationID)
        {
            List<VacationBalanceTable> VacationBalanceTable = new List<VacationBalanceTable>();
            List<BaseVacationsBLL> ExceptionalLeaves = GetByEmployeeCodeVacationTypeNotCanceled(EmployeeCodeID).OrderBy(e => e.VacationStartDate).ToList();

            int index = 0;
            VacationBalanceTable VacationBalanceRow;
            DateTime PreviousRowEndDate = DateTime.Now.Date;
            //VacationStartDat = VacationStartDat.HasValue ? VacationStartDat.Value : Convert.ToDateTime(DateTime.Now.Date, new CultureInfo("en-US"));

            if (!VacationStartDat.HasValue)
            {
                BaseVacationsBLL FirstVacation = new ExceptionalVacationsBLL().GetByEmployeeCodeVacationTypeNotCanceled(EmployeeCodeID).FirstOrDefault();
                if (FirstVacation != null && FirstVacation.VacationID > 0)
                    VacationStartDate = FirstVacation.VacationStartDate;
            }

            // exclude vacation in case of edit 
            if (VacationID > 0)
                ExceptionalLeaves = ExceptionalLeaves.Where(s => s.VacationID != VacationID).ToList();

            foreach (ExceptionalVacationsBLL ExceptionalLeave in ExceptionalLeaves)
            {
                if (index == 0)
                {
                    // User try to get new vacation before the first vacation in vacation table.
                    if (VacationStartDat < ExceptionalLeave.VacationStartDate)
                    {
                        VacationBalanceTable.Add(new VacationBalanceTable()
                        {
                            EmployeeCodeID = EmployeeCodeID,
                            StartDate = VacationStartDat.Value,
                            EndDate = VacationStartDat.Value.AddDays(this.LeaveDaysLimit),
                            ConsumedBalance = 0,
                            RemainingBalance = this.VacationBalance
                        });
                        PreviousRowEndDate = VacationStartDat.Value.AddDays(this.LeaveDaysLimit).AddDays(1);

                        // check if vacation lies between balanceTable rows, if exists update comsumed else added new row
                        VacationBalanceRow = VacationBalanceTable.FirstOrDefault(v => v.StartDate <= ExceptionalLeave.VacationStartDate && v.EndDate >= ExceptionalLeave.VacationEndDate);
                        if (VacationBalanceRow != null && VacationBalanceRow.EmployeeCodeID > 0)
                        {
                            VacationBalanceRow.ConsumedBalance += ExceptionalLeave.VacationPeriod;
                            VacationBalanceRow.RemainingBalance = this.VacationBalance - VacationBalanceRow.ConsumedBalance;
                        }
                        else
                        {
                            VacationBalanceTable.Add(new VacationBalanceTable()
                            {
                                EmployeeCodeID = EmployeeCodeID,
                                StartDate = PreviousRowEndDate,
                                EndDate = PreviousRowEndDate.AddDays(this.LeaveDaysLimit),
                                ConsumedBalance = ExceptionalLeave.VacationPeriod,
                                RemainingBalance = this.VacationBalance - ExceptionalLeave.VacationPeriod
                            });
                            PreviousRowEndDate = ExceptionalLeave.VacationStartDate.AddDays(this.LeaveDaysLimit).AddDays(1);
                        }
                    }
                    else
                    {
                        VacationBalanceTable.Add(new VacationBalanceTable()
                        {
                            EmployeeCodeID = EmployeeCodeID,
                            StartDate = ExceptionalLeave.VacationStartDate,
                            EndDate = ExceptionalLeave.VacationStartDate.AddDays(this.LeaveDaysLimit),
                            ConsumedBalance = ExceptionalLeave.VacationPeriod,
                            RemainingBalance = this.VacationBalance - ExceptionalLeave.VacationPeriod
                        });
                        PreviousRowEndDate = ExceptionalLeave.VacationStartDate.AddDays(this.LeaveDaysLimit).AddDays(1);
                    }
                }
                else
                {
                    // check if vacation lies between balanceTable rows, if exists update comsumed else added new row
                    VacationBalanceRow = VacationBalanceTable.FirstOrDefault(v => v.StartDate <= ExceptionalLeave.VacationStartDate && v.EndDate >= ExceptionalLeave.VacationEndDate);
                    if (VacationBalanceRow != null && VacationBalanceRow.EmployeeCodeID > 0)
                    {
                        VacationBalanceRow.ConsumedBalance += ExceptionalLeave.VacationPeriod;
                        VacationBalanceRow.RemainingBalance = this.VacationBalance - VacationBalanceRow.ConsumedBalance;
                    }
                    else
                    {
                        VacationBalanceTable.Add(new VacationBalanceTable()
                        {
                            EmployeeCodeID = EmployeeCodeID,
                            StartDate = ExceptionalLeave.VacationStartDate,
                            EndDate = ExceptionalLeave.VacationStartDate.AddDays(this.LeaveDaysLimit),
                            ConsumedBalance = ExceptionalLeave.VacationPeriod,
                            RemainingBalance = this.VacationBalance - ExceptionalLeave.VacationPeriod
                        });
                        PreviousRowEndDate = ExceptionalLeave.VacationStartDate.AddDays(this.LeaveDaysLimit).AddDays(1);
                    }
                }
                index++;
            }

            // added new row in BalanceTable if current vacation start date is greater than end date of last row of BalanceTable.
            if (index > 0 && VacationStartDat.HasValue && VacationStartDat.Value >= PreviousRowEndDate)
            {
                VacationBalanceTable.Add(new VacationBalanceTable()
                {
                    EmployeeCodeID = EmployeeCodeID,
                    StartDate = VacationStartDat.Value,
                    EndDate = VacationStartDat.Value.AddDays(this.LeaveDaysLimit),
                    ConsumedBalance = 0,
                    RemainingBalance = this.VacationBalance
                });
            }

            #region Get Last Consumed
            VacationBalanceTable VacationBalanceLastRow;
            if (VacationStartDat.HasValue)
                VacationBalanceLastRow = VacationBalanceTable.OrderByDescending(v => v.StartDate).FirstOrDefault(v => v.StartDate <= VacationStartDat && v.EndDate >= VacationStartDat);
            else
                VacationBalanceLastRow = VacationBalanceTable.OrderByDescending(v => v.StartDate).FirstOrDefault();

            if (VacationBalanceLastRow != null && VacationBalanceLastRow.EmployeeCodeID > 0)
                this.VacationConsumedBalance = VacationBalanceLastRow.ConsumedBalance;
            else
                this.VacationConsumedBalance = 0;
            #endregion

            return VacationBalanceTable;
        }

        public List<ExceptionalVacationsBLL> GetExceptionalVacationsByEmployeeCodeID(int EmployeeCodeID, DateTime StartDate, DateTime EndDate)
        {
            try
            {
                return this.GetByEmployeeCodeID(EmployeeCodeID)
                .Where(
                     x => x.VacationType == this.VacationType & x.IsCanceled == false && (
                        (StartDate >= x.VacationStartDate && StartDate <= x.VacationEndDate) ||
                        (EndDate >= x.VacationStartDate && EndDate <= x.VacationEndDate) ||
                        (StartDate >= x.VacationStartDate && EndDate <= x.VacationEndDate) ||
                        (StartDate <= x.VacationStartDate && EndDate >= x.VacationEndDate))
                      ).Select(x => x as ExceptionalVacationsBLL)
                .ToList();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

