using HCMDAL;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;

namespace HCMBLL
{
    public class AssigningsReasonsBLL : CommonEntity
    {
        public int AssigningReasonID
        {
            get;
            set;
        }

        public string AssigningReasonName
        {
            get;
            set;
        }

        public int Add()
        {
            throw new System.NotImplementedException();
        }

        public int Update()
        {
            throw new System.NotImplementedException();
        }

        public int Remove()
        {
            throw new System.NotImplementedException();
        }

        public List<AssigningsReasonsBLL> GetAssigningsReasons()
        {
            List<AssigningsReasons> AssigningsReasonsList = new AssigningsReasonsDAL().GetAssigningsReasons();
            List<AssigningsReasonsBLL> AssigningsReasonsBLLList = new List<AssigningsReasonsBLL>();
            if (AssigningsReasonsList.Count > 0)
            {
                foreach (var item in AssigningsReasonsList)
                {
                    AssigningsReasonsBLLList.Add(new AssigningsReasonsBLL()
                    {
                        AssigningReasonID = item.AssigningReasonID,
                        AssigningReasonName = item.AssigningReasonName
                    });
                }
            }

            return AssigningsReasonsBLLList;
        }

        public AssigningsReasonsBLL GetByAssigningReasonID(int AssigningReasonID)
        {
            return GetAssigningsReasons().SingleOrDefault(x => x.AssigningReasonID.Equals(AssigningReasonID));
        }

        internal AssigningsReasonsBLL MapAssigningReason(AssigningsReasons AssigningReason)
        {
            try
            {
                AssigningsReasonsBLL AssigningReasonBLL = null;
                if (AssigningReason != null)
                {
                    AssigningReasonBLL = new AssigningsReasonsBLL()
                    {
                        AssigningReasonID = AssigningReason.AssigningReasonID,
                        AssigningReasonName = AssigningReason.AssigningReasonName
                    };
                }
                return AssigningReasonBLL;
            }
            catch
            {
                throw;
            }
        }
    }
}