using HCMBLL.Enums;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMBLL
{
    public static class AssigingsFactory
    {
        public static BaseAssigningsBLL CreateAssigning(AssigningsTypesEnum AssigningType)
        {
            if (AssigningType == AssigningsTypesEnum.Internal)
                return new InternalAssigningBLL();
            else
                return new ExternalAssigningBLL();
        }
    }
}