using HCMDAL;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL
{
    public class QualificationsTypesBLL : CommonEntity
    {
        public virtual int QualificationTypeID
        {
            get;
            set;
        }

        public virtual string QualificationTypeName
        {
            get;
            set;
        }

        public virtual List<QualificationsTypesBLL> GetQualificationsTypes()
        {
            List<QualificationsTypes> QualificationTypeList = new QualificationsTypesDAL().GetQualificationsTypes();
            List<QualificationsTypesBLL> QualificationsTypesBLLList = new List<QualificationsTypesBLL>();
            if (QualificationTypeList.Count > 0)
            {
                foreach (var item in QualificationTypeList)
                {
                    QualificationsTypesBLLList.Add(new QualificationsTypesBLL()
                    {
                        QualificationTypeID = item.QualificationTypeID,
                        QualificationTypeName = item.QualificationTypeName
                    });
                }
            }

            return QualificationsTypesBLLList;
        }

        public QualificationsTypesBLL GetByQualificationTypeID(int QualificationTypeID)
        {
            return GetQualificationsTypes().SingleOrDefault(x => x.QualificationTypeID.Equals(QualificationTypeID));
        }

    }
}

