//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CitiesBLL
{
	public virtual int CityID
	{
		get;
		set;
	}

	public virtual string CityName
	{
		get;
		set;
	}

	public virtual IEnumerable<DelegationsBLL> DelegationsBLL
	{
		get;
		set;
	}

	public virtual CitiesBLL GetByCityID(int CityID)
	{
		throw new System.NotImplementedException();
	}

}

