//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DelegationsBLL : CommonEntity
{
	public virtual int DelegationID
	{
		get;
		set;
	}

	public virtual DateTime DelegationStartDate
	{
		get;
		set;
	}

	public virtual int DelegationPeriod
	{
		get;
		set;
	}

	public virtual DateTime DelegationEndDate
	{
		get;
		set;
	}

	public virtual string DelegationReason
	{
		get;
		set;
	}

	public virtual CitiesBLL City
	{
		get;
		set;
	}

	public virtual EmployeesCodesBLL Employee
	{
		get;
		set;
	}

	private int DelegationBalance
	{
		get;
		set;
	}

	public virtual int RemainingBalance
	{
		get;
		set;
	}

	public virtual int ConsumedBalance
	{
		get;
		set;
	}

	public virtual List<DelegationsBLL> GetDelegations()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

}

