//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EmployeeDelegationBLL 
{
	public virtual EmployeesCodesBLL EmployeeCode
	{
		get;
		set;
	}

	public virtual DateTime DelegationStartDate
	{
		get;
		set;
	}

	public virtual DateTime DelegationEndDate
	{
		get;
		set;
	}

	public virtual int DelegationKindID
	{
		get;
		set;
	}

	public virtual int DelegationFiscalYear 
	{
		get;
		set;
	}

	public virtual int DelegationBalance
	{
		get;
		set;
	}

	public virtual int DelegationRemainingBalance
	{
		get;
		set;
	}

	public virtual int DelegationConsumedBalance
	{
		get;
		set;
	}

	public virtual void EmployeeDelegationBLL(object DateTime, object DateTime, object int, object EmployeesCodesBLL)
	{
		throw new System.NotImplementedException();
	}

	public virtual Result IsValid()
	{
		throw new System.NotImplementedException();
	}

}

