//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EmployeesCodesBLL : CommonEntity
{
	public virtual int EmployeeCodeID
	{
		get;
		set;
	}

	public virtual string EmployeeCodeNo
	{
		get;
		set;
	}

	public virtual EmployeesBLL Employee
	{
		get;
		set;
	}

	public virtual bool IsActive
	{
		get;
		set;
	}

	public virtual EmployeesTypesEnum EmployeeType
	{
		get;
		set;
	}

	public virtual EmployeesCareersHistoryBLL EmployeeCurrentJob
	{
		get;
		set;
	}

	public virtual IEnumerable<BaseAssigningsBLL> BaseAssigningBLL
	{
		get;
		set;
	}

	public virtual EmployeeDelegationBLL EmployeeDelegationBLL
	{
		get;
		set;
	}

	public virtual IEnumerable<OverTimesDetailsBLL> OverTimesDetailsBLL
	{
		get;
		set;
	}

	public virtual IEnumerable<EmployeesCareersHistoryBLL> EmployeesCareersHistoryBLL
	{
		get;
		set;
	}

	public virtual OrganizationsStructureBLL OrganizationsStructureBLL
	{
		get;
		set;
	}

	public virtual EmployeesCodesBLL GetByEmployeeCodeNo(object EmployeesCodesBLL EmployeeCode)
	{
		throw new System.NotImplementedException();
	}

	public virtual EmployeesCodesBLL GetByEmployeeCodeID(object int EmployeeCodeID)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<DelegationsDetailsBLL> GetDelegationsByEmployeeCodeNo(object EmployeesCodesBLL EmployeeCode)
	{
		throw new System.NotImplementedException();
	}

	public virtual Lsit<BaseAssignings> GetAssigningsByEmployeeCodeNo(object EmployeesCodesBLL EmployeeCode)
	{
		throw new System.NotImplementedException();
	}

	public virtual EmployeesCodesBLL GetIsActiveByEmployeeID(object int EmployeeID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetPassengerOrdersByEmployeeCodeNo(List<PassengerOrdersBLL> EployeesCodesBLL EmployeeCode))
	{
		throw new System.NotImplementedException();
	}

}

