//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ExceptionalVacationBLL : BaseVacation, IVacations
{
	private VacationsTypeEnum VacationType
	{
		get;
		set;
	}

	public virtual IEntity Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEntity Cancel()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEntity Extend()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEntity Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEntity Break()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<IVacations> GetByEmployeeCodeID(object int EmployeeCodeID)
	{
		throw new System.NotImplementedException();
	}

}

