//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ExternalAssigningBLL : BaseAssigningBLL
{
	public virtual string ExternalOrganization
	{
		get;
		set;
	}

	public virtual string ExternalCity
	{
		get;
		set;
	}

	public virtual List<ExternalAssigningBLL> GetByEmployeeCodeID(int EmployeeCodeID)
	{
		throw new System.NotImplementedException();
	}

}

