//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IVacations  : IEntity
{
	IEntity Add();

	IEntity Cancel();

	IEntity Extend();

	IEntity Remove();

	IEntity Break();

	List<IVacations> GetByEmployeeCodeID(object int EmployeeCodeID);

}

