//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class JobsGroupsBLL : CommonEntity
{
	public virtual int JobGroupID
	{
		get;
		set;
	}

	public virtual string JobGroupName
	{
		get;
		set;
	}

	public virtual JobsGeneralGroupsBLL JobGeneralGroup
	{
		get;
		set;
	}

	public virtual IEnumerable<JobsCategoriesBLL> JobsCategoriesBLL
	{
		get;
		set;
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<JobsGroupsBLL> GetJobsGroups()
	{
		throw new System.NotImplementedException();
	}

	public virtual JobsGroupsBLL GetByJobGroupID(int JobGroupID)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<JobsGroupsBLL> GetByJobGeneralGroupID(int JobGeneralGroupID)
	{
		throw new System.NotImplementedException();
	}

}

