//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class JobsGeneralGroupsBLL : CommonEntity
{
	public virtual int JobGeneralGroupID
	{
		get;
		set;
	}

	public virtual string JobGeneralGroupName
	{
		get;
		set;
	}

	public virtual IEnumerable<JobsGroupsBLL> JobsGroupsBLL
	{
		get;
		set;
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<JobsGeneralGroupsBLL> GetJobsGeneralGroups()
	{
		throw new System.NotImplementedException();
	}

	public virtual JobsGeneralGroupsBLL GetByJobGeneralGroupID(int JobGeneralGroupID)
	{
		throw new System.NotImplementedException();
	}

}

