//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class JobsBLL : CommonEntity
{
	public virtual int JobID
	{
		get;
		set;
	}

	public virtual string JobName
	{
		get;
		set;
	}

	public virtual JobsCategoriesBLL JobCategory
	{
		get;
		set;
	}

	public virtual IEnumerable<OrganizationsJobsBLL> OrganizationsJobsBLL
	{
		get;
		set;
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<JobsBLL> GetJobs()
	{
		throw new System.NotImplementedException();
	}

	public virtual JobsBLL GetByJobID(int JobID)
	{
		throw new System.NotImplementedException();
	}

	public virtual JobsBLL GetByJobCategoryID(int JobCategoryID)
	{
		throw new System.NotImplementedException();
	}

}

