//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OrganizationsJobsBLL : CommonEntity
{
	public virtual int OrganizationJobID
	{
		get;
		set;
	}

	public virtual bool IsVacant
	{
		get;
		set;
	}

	public virtual RanksBLL Rank
	{
		get;
		set;
	}

	public virtual JobsBLL Job
	{
		get;
		set;
	}

	public virtual OrganizationsStructureBLL OrganizationStructure
	{
		get;
		set;
	}

	public virtual string JobNo
	{
		get;
		set;
	}

	public virtual List<OrganizationsJobsBLL> GetOrganizationJobs()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Update()
	{
		throw new System.NotImplementedException();
	}

	private int ChangeIsVacant()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<OrganizationsJobsBLL> GetVacancyJobs()
	{
		throw new System.NotImplementedException();
	}

}

