//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RanksBLL : CommonEntity
{
	public virtual int RankID
	{
		get;
		set;
	}

	public virtual string RankName
	{
		get;
		set;
	}

	public virtual RanksCategoriesBLL RankCategory
	{
		get;
		set;
	}

	public virtual IEnumerable<OrganizationsJobsBLL> OrganizationsJobsBLL
	{
		get;
		set;
	}

	public virtual List<RanksBLL> GetByRankCategoryID(int RankCategoryID)
	{
		throw new System.NotImplementedException();
	}

	public virtual int Add()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Remove()
	{
		throw new System.NotImplementedException();
	}

	public virtual int Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual RanksBLL GetByRankID(int RankID)
	{
		throw new System.NotImplementedException();
	}

}

