//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum VacationsTypeEnum : int
{
	Normal = 1,
	Exceptional = 2,
	Sick = 4,
	Compulsory = 3,
}
