//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace HCMBLL
{
    public class DelegationPassengerOrderBLL : IPassengerOrderTypeDetails
    {
        public virtual int DetailID
        {
            get;
            set;
        }

        public virtual DelegationsDetailsBLL GetDetails(int DetailID)
        {
            DelegationsDetailsBLL Obj = new DelegationsDetailsBLL();
            Obj.DetailID = DetailID;
            Obj = new DelegationsDetailsBLL().GetDelegationsDetailsByDelegationDetailID(DetailID);
            return Obj;
        }

        public EmployeesCareersHistoryBLL EmployeeCareerHistory
        {
            get;
            set;
        }
    }
}

