CREATE TABLE [dbo].[Assignings] (
    [AssigningID]             INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeCareerHistoryID] INT            NULL,
    [AssigningTypID]          INT            NOT NULL,
    [OrganizationID]          INT            NULL,
    [JobID]                   INT            NULL,
    [AssigningStartDate]      DATE           NOT NULL,
    [AssigningEndDate]        DATE           NULL,
    [ExternalOrganization]    NVARCHAR (50)  NULL,
    [IsFinished]              BIT            NOT NULL,
    [CreatedDate]             DATETIME       CONSTRAINT [DF_Assignings_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]               INT            NULL,
    [LastUpdatedDate]         DATETIME       NULL,
    [LastUpdatedBy]           INT            NULL,
    [AssigningReasonID]       INT            NULL,
    [ExternalKSACityID]       INT            NULL,
    [ManagerCodeID]           INT            NULL,
    [ExternalCity]            NVARCHAR (50)  NULL,
    [AssigningReasonOther]    NVARCHAR (150) NULL,
    CONSTRAINT [PK_Assignings] PRIMARY KEY CLUSTERED ([AssigningID] ASC),
    CONSTRAINT [FK_Assignings_AssigningsReasons] FOREIGN KEY ([AssigningReasonID]) REFERENCES [dbo].[AssigningsReasons] ([AssigningReasonID]),
    CONSTRAINT [FK_Assignings_AssigningTypes] FOREIGN KEY ([AssigningTypID]) REFERENCES [dbo].[AssigningsTypes] ([AssigningTypID]),
    CONSTRAINT [FK_Assignings_EmployeesCareersHistory] FOREIGN KEY ([EmployeeCareerHistoryID]) REFERENCES [dbo].[EmployeesCareersHistory] ([EmployeeCareerHistoryID]),
    CONSTRAINT [FK_Assignings_EmployeesCodes] FOREIGN KEY ([ManagerCodeID]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Assignings_EmployeesCodes1] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]),
    CONSTRAINT [FK_Assignings_EmployeesCodes2] FOREIGN KEY ([LastUpdatedBy]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]),
    CONSTRAINT [FK_Assignings_Jobs] FOREIGN KEY ([JobID]) REFERENCES [dbo].[Jobs] ([JobID]),
    CONSTRAINT [FK_Assignings_KSACities] FOREIGN KEY ([ExternalKSACityID]) REFERENCES [dbo].[KSACities] ([KSACityID]),
    CONSTRAINT [FK_Assignings_OrganizationsStructures] FOREIGN KEY ([OrganizationID]) REFERENCES [dbo].[OrganizationsStructures] ([OrganizationID])
);

