CREATE TABLE [dbo].[Employees] (
    [EmployeeID]                INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeIDNo]              NVARCHAR (11)  NOT NULL,
    [FirstNameAr]               NVARCHAR (100) NOT NULL,
    [MiddleNameAr]              NVARCHAR (100) NOT NULL,
    [GrandFatherNameAr]         NVARCHAR (100) NOT NULL,
    [LastNameAr]                NVARCHAR (100) NOT NULL,
    [FirstNameEn]               NVARCHAR (100) NOT NULL,
    [MiddleNameEn]              NVARCHAR (100) NOT NULL,
    [GrandFatherNameEn]         NVARCHAR (100) NOT NULL,
    [LastNameEn]                NVARCHAR (100) NOT NULL,
    [EmployeeBirthDate]         DATE           NOT NULL,
    [EmployeeMobileNo]          NVARCHAR (50)  NOT NULL,
    [EmployeeBirthPlace]        NVARCHAR (50)  NULL,
    [EmployeeEMail]             NVARCHAR (50)  NULL,
    [EmployeeIDIssueDate]       DATE           NULL,
    [EmployeePassportNo]        NVARCHAR (50)  NULL,
    [EmployeePassportSource]    NVARCHAR (100) NULL,
    [EmployeePassportIssueDate] DATE           NULL,
    [EmployeePassportEndDate]   DATE           NULL,
    [CreatedDate]               DATETIME       CONSTRAINT [DF_Employees_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedDate]           DATETIME       NULL,
    [EmployeeIDExpiryDate]      DATE           NULL,
    [EmployeeIDCopyNo]          INT            NULL,
    [EmployeeIDIssuePlace]      NVARCHAR (100) NULL,
    [DependentCount]            INT            NULL,
    [MaritalStatusID]           INT            NULL,
    [GenderID]                  INT            NULL,
    [NationalityID]             INT            NULL,
    CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    CONSTRAINT [FK_Employees_Genders] FOREIGN KEY ([GenderID]) REFERENCES [dbo].[Genders] ([GenderID]),
    CONSTRAINT [FK_Employees_MaritalStatus] FOREIGN KEY ([MaritalStatusID]) REFERENCES [dbo].[MaritalStatus] ([MaritalStatusID])
);

