CREATE TABLE [dbo].[GovernmentFunds] (
    [GovernmentFundID]          INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeCodeID]            INT            NOT NULL,
    [GovernmentFundTypeID]      INT            NOT NULL,
    [GovernmentDeductionTypeID] INT            NOT NULL,
    [LoanNo]                    NVARCHAR (50)  NOT NULL,
    [LoanDate]                  DATE           NULL,
    [DeductionStartDate]        DATE           NOT NULL,
    [MonthlyDeductionAmount]    FLOAT (53)     NOT NULL,
    [TotalDeductionAmount]      FLOAT (53)     NOT NULL,
    [KSACityID]                 INT            NULL,
    [ContractNo]                NVARCHAR (200) NULL,
    [SponserToName]             NVARCHAR (500) NULL,
    [SponserToIDNo]             NVARCHAR (10)  NULL,
    [IsActive]                  BIT            NULL,
    [DeactiveDate]              DATE           NULL,
    [LetterNo]                  NVARCHAR (200) NULL,
    [LetterDate]                DATE           NULL,
    [Notes]                     NVARCHAR (MAX) NULL,
    [CreatedDate]               DATETIME       CONSTRAINT [DF_GovernmentFunds_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedDate]           DATETIME       NULL,
    [CreatedBy]                 INT            NULL,
    [LastUpdatedBy]             INT            NULL,
    CONSTRAINT [PK_GovernmentFunds] PRIMARY KEY CLUSTERED ([GovernmentFundID] ASC),
    CONSTRAINT [FK_GovernmentFunds_CreatedByNav] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]),
    CONSTRAINT [FK_GovernmentFunds_EmployeesCodes] FOREIGN KEY ([EmployeeCodeID]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]),
    CONSTRAINT [FK_GovernmentFunds_EmployeesCodes2] FOREIGN KEY ([LastUpdatedBy]) REFERENCES [dbo].[EmployeesCodes] ([EmployeeCodeID]),
    CONSTRAINT [FK_GovernmentFunds_GovernmentDeductionTypes] FOREIGN KEY ([GovernmentDeductionTypeID]) REFERENCES [dbo].[GovernmentDeductionsTypes] ([GovernmentDeductionTypeID]),
    CONSTRAINT [FK_GovernmentFunds_GovernmentFundsTypes] FOREIGN KEY ([GovernmentFundTypeID]) REFERENCES [dbo].[GovernmentFundsTypes] ([GovernmentFundTypeID]),
    CONSTRAINT [FK_GovernmentFunds_KSACities] FOREIGN KEY ([KSACityID]) REFERENCES [dbo].[KSACities] ([KSACityID])
);

