

CREATE TABLE [dbo].[SectorsTypes](
	[SectorTypeID] [int] IDENTITY(1,1) NOT NULL,
	[SectorTypeName] [nvarchar](100) NULL,
 CONSTRAINT [PK_SectorsTypes] PRIMARY KEY CLUSTERED 
(
	[SectorTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


