using HCMDAL;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL
{
    public class AllowancesAmountTypesBLL : CommonEntity
    {
        public int AllowanceAmountTypeID
        {
            get;
            set;
        }

        public string AllowanceAmountTypeName
        {
            get;
            set;
        }

        public int Add()
        {
            throw new System.NotImplementedException();
        }

        public int Update()
        {
            throw new System.NotImplementedException();
        }

        public int Remove()
        {
            throw new System.NotImplementedException();
        }

        public List<AllowancesAmountTypesBLL> GetAllowancesAmountTypes()
        {
            List<AllowancesAmountTypes> AllowancesAmountTypesList = new AllowancesAmountTypesDAL().GetAllowancesAmountTypes();
            List<AllowancesAmountTypesBLL> AllowancesAmountTypesBLLList = new List<AllowancesAmountTypesBLL>();
            if (AllowancesAmountTypesList.Count > 0)
            {
                foreach (var item in AllowancesAmountTypesList)
                {
                    AllowancesAmountTypesBLLList.Add(new AllowancesAmountTypesBLL()
                    {
                        AllowanceAmountTypeID = item.AllowanceAmountTypeID,
                        AllowanceAmountTypeName = item.AllowanceAmountTypeName
                    });
                }
            }

            return AllowancesAmountTypesBLLList;
        }

        public AllowancesAmountTypesBLL GetByAllowanceAmountTypeID(int AllowanceAmountTypeID)
        {
            return GetAllowancesAmountTypes().SingleOrDefault(x => x.AllowanceAmountTypeID.Equals(AllowanceAmountTypeID));
        }

        internal AllowancesAmountTypesBLL MapAllowanceAmountType(AllowancesAmountTypes item)
        {
            return item != null ? 
                new AllowancesAmountTypesBLL()
                {
                    AllowanceAmountTypeID = item.AllowanceAmountTypeID,
                    AllowanceAmountTypeName = item.AllowanceAmountTypeName
                } 
                : null;
        }
    }
}