//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssigningsTypes
    {
        public AssigningsTypes()
        {
            this.Assignings = new HashSet<Assignings>();
        }
    
        public int AssigningTypID { get; set; }
        public string AssigningTypeName { get; set; }
    
        public virtual ICollection<Assignings> Assignings { get; set; }
    }
}
