//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        public Branches()
        {
            this.OrganizationsStructures = new HashSet<OrganizationsStructures>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
    
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures { get; set; }
    }
}
