//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSubCategories
    {
        public BusinessSubCategories()
        {
            this.BusinessRules = new HashSet<BusinessRules>();
            this.SMSLogs = new HashSet<SMSLogs>();
        }
    
        public int BusinssSubCategoryID { get; set; }
        public string BusinessSubCategoryAr { get; set; }
        public string BusinessSubCategoryEn { get; set; }
        public int BusinessCategoryID { get; set; }
        public string EntityName { get; set; }
    
        public virtual BusinessCategories BusinessCategories { get; set; }
        public virtual ICollection<BusinessRules> BusinessRules { get; set; }
        public virtual ICollection<SMSLogs> SMSLogs { get; set; }
    }
}
