//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareersHistoryTypes
    {
        public CareersHistoryTypes()
        {
            this.EmployeesCareersHistory = new HashSet<EmployeesCareersHistory>();
        }
    
        public int CareerHistoryTypeID { get; set; }
        public string CareerHistoryTypeName { get; set; }
    
        public virtual ICollection<EmployeesCareersHistory> EmployeesCareersHistory { get; set; }
    }
}
