//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Delegations = new HashSet<Delegations>();
            this.InternshipScholarships = new HashSet<InternshipScholarships>();
            this.Scholarships = new HashSet<Scholarships>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual ICollection<Delegations> Delegations { get; set; }
        public virtual ICollection<InternshipScholarships> InternshipScholarships { get; set; }
        public virtual ICollection<Scholarships> Scholarships { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
