//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesOldJobs
    {
        public int EmployeeOldJobID { get; set; }
        public int EmployeeCodeID { get; set; }
        public string JobName { get; set; }
        public string OrganizationName { get; set; }
        public string RankName { get; set; }
        public string CareerDegreeName { get; set; }
        public Nullable<System.DateTime> EmployeeOldJobStartDate { get; set; }
        public Nullable<System.DateTime> EmployeeOldJobEndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual EmployeesCodes EmployeesCodes { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
    }
}
