//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperiencesWithDetails
    {
        public int EmployeeExperienceWithDetailID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int SectorTypeID { get; set; }
        public string SectorName { get; set; }
        public string JobName { get; set; }
        public int EmployeeCodeID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual EmployeesCodes EmployeesCodes { get; set; }
        public virtual SectorsTypes SectorsTypes { get; set; }
        public virtual EmployeesCodes EmployeesCodes1 { get; set; }
    }
}
