//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesUnderPrivateCompanies
    {
        public int EmployeeUnderPrivateCompanyID { get; set; }
        public string EmployeeCodeNo { get; set; }
        public string EmployeeIDNo { get; set; }
        public string NameAr { get; set; }
        public string GenderName { get; set; }
        public string OrganizationName { get; set; }
        public string RankName { get; set; }
        public string JobName { get; set; }
        public string Department { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal TotalSalary { get; set; }
        public string QualificationDegreeName { get; set; }
        public string QualificationName { get; set; }
        public string ExactSpecialization { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public decimal RemainingNormalVacationBalance { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
