//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesCodes
    {
        public EmployeesCodes()
        {
            this.OrganizationsStructures = new HashSet<OrganizationsStructures>();
            this.EmployeesCareersHistory = new HashSet<EmployeesCareersHistory>();
            this.Scholarships = new HashSet<Scholarships>();
            this.Delegations = new HashSet<Delegations>();
            this.Delegations1 = new HashSet<Delegations>();
            this.EmployeesAllowances = new HashSet<EmployeesAllowances>();
            this.EmployeesAllowances1 = new HashSet<EmployeesAllowances>();
            this.EmployeesCareersHistory1 = new HashSet<EmployeesCareersHistory>();
            this.EmployeesCareersHistory2 = new HashSet<EmployeesCareersHistory>();
            this.InternshipScholarships = new HashSet<InternshipScholarships>();
            this.InternshipScholarships1 = new HashSet<InternshipScholarships>();
            this.PassengerOrders = new HashSet<PassengerOrders>();
            this.PassengerOrders1 = new HashSet<PassengerOrders>();
            this.OverTimes = new HashSet<OverTimes>();
            this.OverTimes1 = new HashSet<OverTimes>();
            this.OverTimesDetails = new HashSet<OverTimesDetails>();
            this.OrganizationsStructures1 = new HashSet<OrganizationsStructures>();
            this.OrganizationsStructures2 = new HashSet<OrganizationsStructures>();
            this.SMSLogs = new HashSet<SMSLogs>();
            this.Vacations = new HashSet<Vacations>();
            this.VacationsDetails = new HashSet<VacationsDetails>();
            this.VacationsDetails1 = new HashSet<VacationsDetails>();
            this.Vacations1 = new HashSet<Vacations>();
            this.VacationsDetails2 = new HashSet<VacationsDetails>();
            this.EmployeesVacationsOpeningBalances = new HashSet<EmployeesVacationsOpeningBalances>();
            this.GovernmentFunds = new HashSet<GovernmentFunds>();
            this.GovernmentFunds1 = new HashSet<GovernmentFunds>();
            this.GovernmentFunds2 = new HashSet<GovernmentFunds>();
            this.ScholarshipsDetails = new HashSet<ScholarshipsDetails>();
            this.ScholarshipsDetails1 = new HashSet<ScholarshipsDetails>();
            this.HolidaysSettings = new HashSet<HolidaysSettings>();
            this.HolidaysSettings1 = new HashSet<HolidaysSettings>();
            this.HolidaysAttendance = new HashSet<HolidaysAttendance>();
            this.HolidaysAttendance1 = new HashSet<HolidaysAttendance>();
            this.Scholarships1 = new HashSet<Scholarships>();
            this.OverTimesDetails2 = new HashSet<OverTimesDetails>();
            this.Assignings = new HashSet<Assignings>();
            this.Assignings1 = new HashSet<Assignings>();
            this.Assignings2 = new HashSet<Assignings>();
            this.SportsSeasons = new HashSet<SportsSeasons>();
            this.EndOfServices = new HashSet<EndOfServices>();
            this.EndOfServices1 = new HashSet<EndOfServices>();
            this.PromotionsJobsCategories = new HashSet<PromotionsJobsCategories>();
            this.EmployeesQualifications = new HashSet<EmployeesQualifications>();
            this.EmployeesExperiences = new HashSet<EmployeesExperiences>();
            this.EmployeesExperiences1 = new HashSet<EmployeesExperiences>();
            this.JobsCategoriesQualifications = new HashSet<JobsCategoriesQualifications>();
            this.JobsCategoriesQualifications1 = new HashSet<JobsCategoriesQualifications>();
            this.EmployeesEvaluations = new HashSet<EmployeesEvaluations>();
            this.EmployeesEvaluations1 = new HashSet<EmployeesEvaluations>();
            this.ExactSpecializations = new HashSet<ExactSpecializations>();
            this.EndOfServicesVacations = new HashSet<EndOfServicesVacations>();
            this.EndOfServicesVacations1 = new HashSet<EndOfServicesVacations>();
            this.GeneralSpecializations = new HashSet<GeneralSpecializations>();
            this.Qualifications = new HashSet<Qualifications>();
            this.QualificationsDegrees = new HashSet<QualificationsDegrees>();
            this.PromotionsRecords = new HashSet<PromotionsRecords>();
            this.PromotionsRecords1 = new HashSet<PromotionsRecords>();
            this.PromotionsRecords2 = new HashSet<PromotionsRecords>();
            this.PromotionsRecords3 = new HashSet<PromotionsRecords>();
            this.PromotionsRecords4 = new HashSet<PromotionsRecords>();
            this.PromotionsRecords5 = new HashSet<PromotionsRecords>();
            this.PromotionsRecordsEmployees = new HashSet<PromotionsRecordsEmployees>();
            this.PromotionsRecordsEmployees1 = new HashSet<PromotionsRecordsEmployees>();
            this.PromotionsRecordsEmployees2 = new HashSet<PromotionsRecordsEmployees>();
            this.PromotionsRecordsEmployees3 = new HashSet<PromotionsRecordsEmployees>();
            this.PromotionsRecordsEmployees4 = new HashSet<PromotionsRecordsEmployees>();
            this.PromotionsPeriods = new HashSet<PromotionsPeriods>();
            this.EmployeesQualifications1 = new HashSet<EmployeesQualifications>();
            this.PromotionsRecordsLogs = new HashSet<PromotionsRecordsLogs>();
            this.StopWorks = new HashSet<StopWorks>();
            this.StopWorks1 = new HashSet<StopWorks>();
            this.EmployeesDegreesUpgrades = new HashSet<EmployeesDegreesUpgrades>();
            this.Teachers = new HashSet<Teachers>();
            this.Teachers1 = new HashSet<Teachers>();
            this.PromotionCardsPrinting = new HashSet<PromotionCardsPrinting>();
            this.PromotionCardsPrinting1 = new HashSet<PromotionCardsPrinting>();
            this.PromotionCardsPrinting2 = new HashSet<PromotionCardsPrinting>();
            this.InsteadDeportations = new HashSet<InsteadDeportations>();
            this.InsteadDeportations1 = new HashSet<InsteadDeportations>();
            this.ContractorsBasicSalaries = new HashSet<ContractorsBasicSalaries>();
            this.EmployeeExperiencesWithDetails = new HashSet<EmployeeExperiencesWithDetails>();
            this.EmployeeExperiencesWithDetails1 = new HashSet<EmployeeExperiencesWithDetails>();
            this.ContractorsBasicSalaries1 = new HashSet<ContractorsBasicSalaries>();
            this.ContractorsBasicSalaries2 = new HashSet<ContractorsBasicSalaries>();
            this.Allowances = new HashSet<Allowances>();
            this.Allowances1 = new HashSet<Allowances>();
            this.Employees1 = new HashSet<Employees>();
            this.Employees11 = new HashSet<Employees>();
            this.Ranks = new HashSet<Ranks>();
            this.Ranks1 = new HashSet<Ranks>();
            this.Transfers = new HashSet<Transfers>();
            this.Transfers1 = new HashSet<Transfers>();
            this.JobsAllowances = new HashSet<JobsAllowances>();
            this.JobsAllowances1 = new HashSet<JobsAllowances>();
            this.Scholarships2 = new HashSet<Scholarships>();
            this.EVacationsRequests = new HashSet<EVacationsRequests>();
            this.EVacationsRequests1 = new HashSet<EVacationsRequests>();
            this.EVacationsRequests2 = new HashSet<EVacationsRequests>();
            this.OrganizationsStructures3 = new HashSet<OrganizationsStructures>();
            this.OrganizationsStructures11 = new HashSet<OrganizationsStructures>();
            this.Lenders = new HashSet<Lenders>();
            this.Lenders1 = new HashSet<Lenders>();
            this.EServicesAuthorizations = new HashSet<EServicesAuthorizations>();
            this.EServicesAuthorizations1 = new HashSet<EServicesAuthorizations>();
            this.EServicesAuthorizations2 = new HashSet<EServicesAuthorizations>();
            this.EServicesProxies = new HashSet<EServicesProxies>();
            this.EServicesProxies1 = new HashSet<EServicesProxies>();
            this.EServicesProxies2 = new HashSet<EServicesProxies>();
            this.EServicesProxies3 = new HashSet<EServicesProxies>();
            this.OrganizationsManagers = new HashSet<OrganizationsManagers>();
            this.OrganizationsManagers1 = new HashSet<OrganizationsManagers>();
            this.OrganizationsManagers2 = new HashSet<OrganizationsManagers>();
            this.EmployeesOldJobs = new HashSet<EmployeesOldJobs>();
            this.EmployeesOldJobs1 = new HashSet<EmployeesOldJobs>();
            this.EmployeesOldJobs2 = new HashSet<EmployeesOldJobs>();
        }
    
        public int EmployeeCodeID { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeCodeNo { get; set; }
        public int EmployeeTypeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual EmployeesTypes EmployeesTypes { get; set; }
        public virtual ICollection<EmployeesCareersHistory> EmployeesCareersHistory { get; set; }
        public virtual ICollection<Scholarships> Scholarships { get; set; }
        public virtual ICollection<Delegations> Delegations { get; set; }
        public virtual ICollection<Delegations> Delegations1 { get; set; }
        public virtual ICollection<EmployeesAllowances> EmployeesAllowances { get; set; }
        public virtual ICollection<EmployeesAllowances> EmployeesAllowances1 { get; set; }
        public virtual ICollection<EmployeesCareersHistory> EmployeesCareersHistory1 { get; set; }
        public virtual ICollection<EmployeesCareersHistory> EmployeesCareersHistory2 { get; set; }
        public virtual ICollection<InternshipScholarships> InternshipScholarships { get; set; }
        public virtual ICollection<InternshipScholarships> InternshipScholarships1 { get; set; }
        public virtual ICollection<PassengerOrders> PassengerOrders { get; set; }
        public virtual ICollection<PassengerOrders> PassengerOrders1 { get; set; }
        public virtual ICollection<OverTimes> OverTimes { get; set; }
        public virtual ICollection<OverTimes> OverTimes1 { get; set; }
        public virtual ICollection<OverTimesDetails> OverTimesDetails { get; set; }
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures1 { get; set; }
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures2 { get; set; }
        public virtual ICollection<SMSLogs> SMSLogs { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
        public virtual ICollection<VacationsDetails> VacationsDetails { get; set; }
        public virtual ICollection<VacationsDetails> VacationsDetails1 { get; set; }
        public virtual ICollection<Vacations> Vacations1 { get; set; }
        public virtual ICollection<VacationsDetails> VacationsDetails2 { get; set; }
        public virtual ICollection<EmployeesVacationsOpeningBalances> EmployeesVacationsOpeningBalances { get; set; }
        public virtual ICollection<GovernmentFunds> GovernmentFunds { get; set; }
        public virtual ICollection<GovernmentFunds> GovernmentFunds1 { get; set; }
        public virtual ICollection<GovernmentFunds> GovernmentFunds2 { get; set; }
        public virtual ICollection<ScholarshipsDetails> ScholarshipsDetails { get; set; }
        public virtual ICollection<ScholarshipsDetails> ScholarshipsDetails1 { get; set; }
        public virtual ICollection<HolidaysSettings> HolidaysSettings { get; set; }
        public virtual ICollection<HolidaysSettings> HolidaysSettings1 { get; set; }
        public virtual ICollection<HolidaysAttendance> HolidaysAttendance { get; set; }
        public virtual ICollection<HolidaysAttendance> HolidaysAttendance1 { get; set; }
        public virtual ICollection<Scholarships> Scholarships1 { get; set; }
        public virtual ICollection<OverTimesDetails> OverTimesDetails2 { get; set; }
        public virtual ICollection<Assignings> Assignings { get; set; }
        public virtual ICollection<Assignings> Assignings1 { get; set; }
        public virtual ICollection<Assignings> Assignings2 { get; set; }
        public virtual ICollection<SportsSeasons> SportsSeasons { get; set; }
        public virtual ICollection<EndOfServices> EndOfServices { get; set; }
        public virtual ICollection<EndOfServices> EndOfServices1 { get; set; }
        public virtual ICollection<PromotionsJobsCategories> PromotionsJobsCategories { get; set; }
        public virtual ICollection<EmployeesQualifications> EmployeesQualifications { get; set; }
        public virtual ICollection<EmployeesExperiences> EmployeesExperiences { get; set; }
        public virtual ICollection<EmployeesExperiences> EmployeesExperiences1 { get; set; }
        public virtual ICollection<JobsCategoriesQualifications> JobsCategoriesQualifications { get; set; }
        public virtual ICollection<JobsCategoriesQualifications> JobsCategoriesQualifications1 { get; set; }
        public virtual ICollection<EmployeesEvaluations> EmployeesEvaluations { get; set; }
        public virtual ICollection<EmployeesEvaluations> EmployeesEvaluations1 { get; set; }
        public virtual ICollection<ExactSpecializations> ExactSpecializations { get; set; }
        public virtual ICollection<EndOfServicesVacations> EndOfServicesVacations { get; set; }
        public virtual ICollection<EndOfServicesVacations> EndOfServicesVacations1 { get; set; }
        public virtual ICollection<GeneralSpecializations> GeneralSpecializations { get; set; }
        public virtual ICollection<Qualifications> Qualifications { get; set; }
        public virtual ICollection<QualificationsDegrees> QualificationsDegrees { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords1 { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords2 { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords3 { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords4 { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords5 { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees1 { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees2 { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees3 { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees4 { get; set; }
        public virtual ICollection<PromotionsPeriods> PromotionsPeriods { get; set; }
        public virtual ICollection<EmployeesQualifications> EmployeesQualifications1 { get; set; }
        public virtual ICollection<PromotionsRecordsLogs> PromotionsRecordsLogs { get; set; }
        public virtual ICollection<StopWorks> StopWorks { get; set; }
        public virtual ICollection<StopWorks> StopWorks1 { get; set; }
        public virtual ICollection<EmployeesDegreesUpgrades> EmployeesDegreesUpgrades { get; set; }
        public virtual ICollection<Teachers> Teachers { get; set; }
        public virtual ICollection<Teachers> Teachers1 { get; set; }
        public virtual ICollection<PromotionCardsPrinting> PromotionCardsPrinting { get; set; }
        public virtual ICollection<PromotionCardsPrinting> PromotionCardsPrinting1 { get; set; }
        public virtual ICollection<PromotionCardsPrinting> PromotionCardsPrinting2 { get; set; }
        public virtual ICollection<InsteadDeportations> InsteadDeportations { get; set; }
        public virtual ICollection<InsteadDeportations> InsteadDeportations1 { get; set; }
        public virtual ICollection<ContractorsBasicSalaries> ContractorsBasicSalaries { get; set; }
        public virtual ICollection<EmployeeExperiencesWithDetails> EmployeeExperiencesWithDetails { get; set; }
        public virtual ICollection<EmployeeExperiencesWithDetails> EmployeeExperiencesWithDetails1 { get; set; }
        public virtual ICollection<ContractorsBasicSalaries> ContractorsBasicSalaries1 { get; set; }
        public virtual ICollection<ContractorsBasicSalaries> ContractorsBasicSalaries2 { get; set; }
        public virtual ICollection<Allowances> Allowances { get; set; }
        public virtual ICollection<Allowances> Allowances1 { get; set; }
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual ICollection<Employees> Employees11 { get; set; }
        public virtual ICollection<Ranks> Ranks { get; set; }
        public virtual ICollection<Ranks> Ranks1 { get; set; }
        public virtual ICollection<Transfers> Transfers { get; set; }
        public virtual ICollection<Transfers> Transfers1 { get; set; }
        public virtual ICollection<JobsAllowances> JobsAllowances { get; set; }
        public virtual ICollection<JobsAllowances> JobsAllowances1 { get; set; }
        public virtual ICollection<Scholarships> Scholarships2 { get; set; }
        public virtual ICollection<EVacationsRequests> EVacationsRequests { get; set; }
        public virtual ICollection<EVacationsRequests> EVacationsRequests1 { get; set; }
        public virtual ICollection<EVacationsRequests> EVacationsRequests2 { get; set; }
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures3 { get; set; }
        public virtual ICollection<OrganizationsStructures> OrganizationsStructures11 { get; set; }
        public virtual ICollection<Lenders> Lenders { get; set; }
        public virtual ICollection<Lenders> Lenders1 { get; set; }
        public virtual ICollection<EServicesAuthorizations> EServicesAuthorizations { get; set; }
        public virtual ICollection<EServicesAuthorizations> EServicesAuthorizations1 { get; set; }
        public virtual ICollection<EServicesAuthorizations> EServicesAuthorizations2 { get; set; }
        public virtual ICollection<EServicesProxies> EServicesProxies { get; set; }
        public virtual ICollection<EServicesProxies> EServicesProxies1 { get; set; }
        public virtual ICollection<EServicesProxies> EServicesProxies2 { get; set; }
        public virtual ICollection<EServicesProxies> EServicesProxies3 { get; set; }
        public virtual ICollection<OrganizationsManagers> OrganizationsManagers { get; set; }
        public virtual ICollection<OrganizationsManagers> OrganizationsManagers1 { get; set; }
        public virtual ICollection<OrganizationsManagers> OrganizationsManagers2 { get; set; }
        public virtual ICollection<EmployeesOldJobs> EmployeesOldJobs { get; set; }
        public virtual ICollection<EmployeesOldJobs> EmployeesOldJobs1 { get; set; }
        public virtual ICollection<EmployeesOldJobs> EmployeesOldJobs2 { get; set; }
    }
}
