//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.EmployeesCodes = new HashSet<EmployeesCodes>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeIDNo { get; set; }
        public string FirstNameAr { get; set; }
        public string MiddleNameAr { get; set; }
        public string GrandFatherNameAr { get; set; }
        public string LastNameAr { get; set; }
        public string FirstNameEn { get; set; }
        public string MiddleNameEn { get; set; }
        public string GrandFatherNameEn { get; set; }
        public string LastNameEn { get; set; }
        public System.DateTime EmployeeBirthDate { get; set; }
        public string EmployeeMobileNo { get; set; }
        public string EmployeeBirthPlace { get; set; }
        public string EmployeeEMail { get; set; }
        public Nullable<System.DateTime> EmployeeIDIssueDate { get; set; }
        public string EmployeePassportNo { get; set; }
        public string EmployeePassportSource { get; set; }
        public Nullable<System.DateTime> EmployeePassportIssueDate { get; set; }
        public Nullable<System.DateTime> EmployeePassportEndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> EmployeeIDExpiryDate { get; set; }
        public Nullable<int> EmployeeIDCopyNo { get; set; }
        public string EmployeeIDIssuePlace { get; set; }
        public Nullable<int> DependentCount { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string FifthNameAr { get; set; }
        public string FifthNameEn { get; set; }
    
        public virtual ICollection<EmployeesCodes> EmployeesCodes { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Countries Nationalities { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
    }
}
