//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfServices
    {
        public EndOfServices()
        {
            this.EndOfServicesVacations = new HashSet<EndOfServicesVacations>();
        }
    
        public int EndOfServiceID { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
        public System.DateTime EndOfServiceDate { get; set; }
        public string EndOfServiceDecisionNo { get; set; }
        public System.DateTime EndOfServiceDecisionDate { get; set; }
        public int EndOfServiceReasonID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<bool> isProcessed { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
        public virtual EndOfServicesReasons EndOfServicesReasons { get; set; }
        public virtual ICollection<EndOfServicesVacations> EndOfServicesVacations { get; set; }
    }
}
