//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfServicesReasons
    {
        public EndOfServicesReasons()
        {
            this.EndOfServices = new HashSet<EndOfServices>();
        }
    
        public int EndOfServiceReasonID { get; set; }
        public int EndOfServiceCaseID { get; set; }
        public string EndOfServiceReason { get; set; }
    
        public virtual ICollection<EndOfServices> EndOfServices { get; set; }
        public virtual EndOfServicesCases EndOfServicesCases { get; set; }
    }
}
