//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EServicesProxies
    {
        public int EServiceProxyID { get; set; }
        public int EServiceTypeID { get; set; }
        public int FromEmployeeCodeID { get; set; }
        public int ToEmployeeCodeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int EServiceProxyStatusID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string Notes { get; set; }
        public string CancellationReason { get; set; }
    
        public virtual EmployeesCodes FromEmployeeCode { get; set; }
        public virtual EmployeesCodes ToEmployeeCode { get; set; }
        public virtual EServicesProxiesStatus EServicesProxiesStatus { get; set; }
        public virtual EServicesTypes EServicesTypes { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
    }
}
