//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVacationsRequests
    {
        public EVacationsRequests()
        {
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int EVacationRequestID { get; set; }
        public int EVacationRequestNo { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
        public System.DateTime VacationStartDate { get; set; }
        public System.DateTime VacationEndDate { get; set; }
        public int VacationTypeID { get; set; }
        public int OldBalanceConsumed { get; set; }
        public string CreatorNotes { get; set; }
        public Nullable<System.DateTime> ApprovalDateTime { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApproverNotes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> EVacationRequestStatusID { get; set; }
        public Nullable<int> ActualOrganizationID { get; set; }
        public Nullable<int> ActualJobID { get; set; }
        public string CancellationReasonByHR { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual EmployeesCodes ApprovedByNav { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
        public virtual VacationsTypes VacationsTypes { get; set; }
        public virtual EVacationRequestsStatus EVacationRequestsStatus { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual OrganizationsStructures OrganizationsStructures { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
