//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationPoints
    {
        public EvaluationPoints()
        {
            this.EmployeesEvaluations = new HashSet<EmployeesEvaluations>();
        }
    
        public int EvaluationPointID { get; set; }
        public string Evaluation { get; set; }
        public double EvaluationPoint { get; set; }
        public bool IsExcludedFromPromotion { get; set; }
    
        public virtual ICollection<EmployeesEvaluations> EmployeesEvaluations { get; set; }
    }
}
