//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovernmentFundsTypes
    {
        public GovernmentFundsTypes()
        {
            this.GovernmentFunds = new HashSet<GovernmentFunds>();
        }
    
        public int GovernmentFundTypeID { get; set; }
        public string GovernmentFundTypeName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual ICollection<GovernmentFunds> GovernmentFunds { get; set; }
    }
}
