//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovernmentDeductionsTypes
    {
        public GovernmentDeductionsTypes()
        {
            this.GovernmentFunds = new HashSet<GovernmentFunds>();
        }
    
        public int GovernmentDeductionTypeID { get; set; }
        public string GovernmentDeductionTypeName { get; set; }
    
        public virtual ICollection<GovernmentFunds> GovernmentFunds { get; set; }
    }
}
