//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidaysAttendanceDetails
    {
        public HolidaysAttendanceDetails()
        {
            this.Vacations = new HashSet<Vacations>();
        }
    
        public int HolidayAttendanceDetailID { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
        public int HolidayAttendanceID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual HolidaysAttendance HolidaysAttendance { get; set; }
        public virtual ICollection<Vacations> Vacations { get; set; }
    }
}
