//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lenders
    {
        public int LenderID { get; set; }
        public System.DateTime LenderStartDate { get; set; }
        public System.DateTime LenderEndDate { get; set; }
        public Nullable<int> KSACityID { get; set; }
        public string LenderOrganization { get; set; }
        public bool IsFinished { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string LenderEndReason { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
        public virtual KSACities KSACities { get; set; }
    }
}
