//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsPeriods
    {
        public PromotionsPeriods()
        {
            this.PromotionsJobsCategories = new HashSet<PromotionsJobsCategories>();
            this.PromotionsRecords = new HashSet<PromotionsRecords>();
            this.JobsCategoriesQualifications = new HashSet<JobsCategoriesQualifications>();
            this.PromotionCardsPrinting = new HashSet<PromotionCardsPrinting>();
        }
    
        public int PromotionPeriodID { get; set; }
        public int PeriodID { get; set; }
        public int YearID { get; set; }
        public System.DateTime PromotionStartDate { get; set; }
        public System.DateTime PromotionEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual EmployeesCodes EmployeesCodes { get; set; }
        public virtual MaturityYearsBalances MaturityYearsBalances { get; set; }
        public virtual Periods Periods { get; set; }
        public virtual ICollection<PromotionsJobsCategories> PromotionsJobsCategories { get; set; }
        public virtual ICollection<PromotionsRecords> PromotionsRecords { get; set; }
        public virtual ICollection<JobsCategoriesQualifications> JobsCategoriesQualifications { get; set; }
        public virtual ICollection<PromotionCardsPrinting> PromotionCardsPrinting { get; set; }
    }
}
