//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsRecordsJobsVacancies
    {
        public PromotionsRecordsJobsVacancies()
        {
            this.PromotionsRecordsEmployees = new HashSet<PromotionsRecordsEmployees>();
        }
    
        public int PromotionRecordJobVacancyID { get; set; }
        public int OrganizationJobID { get; set; }
        public int PromotionRecordID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual PromotionsRecords PromotionsRecords { get; set; }
        public virtual ICollection<PromotionsRecordsEmployees> PromotionsRecordsEmployees { get; set; }
        public virtual OrganizationsJobs OrganizationsJobs { get; set; }
    }
}
