//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsRecordsStatus
    {
        public PromotionsRecordsStatus()
        {
            this.PromotionsRecords = new HashSet<PromotionsRecords>();
        }
    
        public int PromotionRecordStatusID { get; set; }
        public string PromotionRecordStatusName { get; set; }
    
        public virtual ICollection<PromotionsRecords> PromotionsRecords { get; set; }
    }
}
