//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsRecordsEmployeesEducationsDetails
    {
        public int PromotionRecordEmployeeEducationDetailID { get; set; }
        public int PromotionRecordEmployeeID { get; set; }
        public int QualificationDegreeID { get; set; }
        public int QualificationID { get; set; }
        public int GeneralSpecializationID { get; set; }
        public int Weight { get; set; }
        public decimal Points { get; set; }
        public bool IsIncluded { get; set; }
    
        public virtual GeneralSpecializations GeneralSpecializations { get; set; }
        public virtual PromotionsRecordsEmployees PromotionsRecordsEmployees { get; set; }
        public virtual Qualifications Qualifications { get; set; }
        public virtual QualificationsDegrees QualificationsDegrees { get; set; }
    }
}
