//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsRecordsLogs
    {
        public int PromotionRecordLogID { get; set; }
        public int PromotionRecordID { get; set; }
        public string PromotionRecordNo { get; set; }
        public string ActionDescription { get; set; }
        public int PromotionRecordActionTypeID { get; set; }
        public int ActionBy { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual PromotionsRecordsActionsTypes PromotionsRecordsActionsTypes { get; set; }
        public virtual EmployeesCodes ActionByNav { get; set; }
    }
}
