//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RanksCategories
    {
        public RanksCategories()
        {
            this.Ranks = new HashSet<Ranks>();
            this.RanksCategoriesVacationsBalances = new HashSet<RanksCategoriesVacationsBalances>();
        }
    
        public int RankCategoryID { get; set; }
        public string RankCategoryName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string RankCategoryNameEn { get; set; }
        public Nullable<double> RetirementPercentage { get; set; }
    
        public virtual ICollection<Ranks> Ranks { get; set; }
        public virtual ICollection<RanksCategoriesVacationsBalances> RanksCategoriesVacationsBalances { get; set; }
    }
}
