//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLogs
    {
        public int SMSLogID { get; set; }
        public int BusinssSubCategoryID { get; set; }
        public int DetailID { get; set; }
        public string Message { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual BusinessSubCategories BusinessSubCategories { get; set; }
        public virtual EmployeesCodes EmployeesCodes { get; set; }
    }
}
