//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopWorksCategories
    {
        public StopWorksCategories()
        {
            this.StopWorksTypes = new HashSet<StopWorksTypes>();
        }
    
        public int StopWorkCategoryID { get; set; }
        public string StopWorkCategoryName { get; set; }
    
        public virtual ICollection<StopWorksTypes> StopWorksTypes { get; set; }
    }
}
