//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopWorks
    {
        public int StopWorkID { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
        public int StopWorkTypeID { get; set; }
        public System.DateTime StopWorkStartDate { get; set; }
        public Nullable<System.DateTime> StopWorkEndDate { get; set; }
        public string StopPoint { get; set; }
        public Nullable<bool> IsConvicted { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string StartStopWorkDecisionNumber { get; set; }
        public Nullable<System.DateTime> StartStopWorkDecisionDate { get; set; }
        public string EndStopWorkDecisionNumber { get; set; }
        public Nullable<System.DateTime> EndStopWorkDecisionDate { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
        public virtual StopWorksTypes StopWorksTypes { get; set; }
    }
}
