//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsClasses
    {
        public TicketsClasses()
        {
            this.RanksTicketsClasses = new HashSet<RanksTicketsClasses>();
            this.PassengerOrders = new HashSet<PassengerOrders>();
        }
    
        public int TicketClassID { get; set; }
        public string TicketClassName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual ICollection<RanksTicketsClasses> RanksTicketsClasses { get; set; }
        public virtual ICollection<PassengerOrders> PassengerOrders { get; set; }
    }
}
