//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations
    {
        public Vacations()
        {
            this.VacationsDetails = new HashSet<VacationsDetails>();
        }
    
        public int VacationID { get; set; }
        public int EmployeeCareerHistoryID { get; set; }
        public int VacationTypeID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime VacationStartDate { get; set; }
        public System.DateTime VacationEndDate { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> OldBalanceConsumed { get; set; }
        public Nullable<int> InAdvConsumed { get; set; }
        public Nullable<int> SickVacationTypeID { get; set; }
        public Nullable<System.DateTime> StudiesVacationStartDate { get; set; }
        public Nullable<int> HolidayAttendanceDetailID { get; set; }
        public Nullable<int> SportsSeasonID { get; set; }
        public Nullable<int> NormalVacationTypeID { get; set; }
        public Nullable<bool> IsSickLeaveAmountPaid { get; set; }
        public Nullable<int> EVacationRequestID { get; set; }
    
        public virtual EmployeesCareersHistory EmployeesCareersHistory { get; set; }
        public virtual EmployeesCodes CreatedByNav { get; set; }
        public virtual VacationsTypes VacationsTypes { get; set; }
        public virtual ICollection<VacationsDetails> VacationsDetails { get; set; }
        public virtual EmployeesCodes LastUpdatedByNav { get; set; }
        public virtual SickVacationsTypes SickVacationsTypes { get; set; }
        public virtual HolidaysAttendanceDetails HolidaysAttendanceDetails { get; set; }
        public virtual SportsSeasons SportsSeasons { get; set; }
        public virtual NormalVacationsTypes NormalVacationsTypes { get; set; }
        public virtual EVacationsRequests EVacationsRequests { get; set; }
    }
}
