//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationsTypes
    {
        public VacationsTypes()
        {
            this.Vacations = new HashSet<Vacations>();
            this.EmployeesVacationsOpeningBalances = new HashSet<EmployeesVacationsOpeningBalances>();
            this.EndOfServicesVacations = new HashSet<EndOfServicesVacations>();
            this.RanksCategoriesVacationsBalances = new HashSet<RanksCategoriesVacationsBalances>();
            this.EVacationsRequests = new HashSet<EVacationsRequests>();
        }
    
        public int VacationTypeID { get; set; }
        public string VacationTypeName { get; set; }
        public Nullable<bool> IsForFemaleOnly { get; set; }
        public Nullable<bool> IsPossibleTobeCreatedFromEVacationRequest { get; set; }
    
        public virtual ICollection<Vacations> Vacations { get; set; }
        public virtual ICollection<EmployeesVacationsOpeningBalances> EmployeesVacationsOpeningBalances { get; set; }
        public virtual ICollection<EndOfServicesVacations> EndOfServicesVacations { get; set; }
        public virtual ICollection<RanksCategoriesVacationsBalances> RanksCategoriesVacationsBalances { get; set; }
        public virtual ICollection<EVacationsRequests> EVacationsRequests { get; set; }
    }
}
