//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationsActions
    {
        public VacationsActions()
        {
            this.VacationsDetails = new HashSet<VacationsDetails>();
        }
    
        public int VacationActionID { get; set; }
        public string VacationActionName { get; set; }
    
        public virtual ICollection<VacationsDetails> VacationsDetails { get; set; }
    }
}
