//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQualificationsBasedOnAssignings
    {
        public string RankCategoryName { get; set; }
        public string EmployeeCodeNo { get; set; }
        public string EmployeeIDNo { get; set; }
        public string EmployeeNameAr { get; set; }
        public string QualificationDegreeName { get; set; }
        public string QualificationName { get; set; }
        public string GeneralSpecializationName { get; set; }
        public string RankName { get; set; }
        public string JobName { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> QualificationID { get; set; }
        public Nullable<int> QualificationDegreeID { get; set; }
        public int RankCategoryID { get; set; }
        public int RankID { get; set; }
        public Nullable<int> GeneralSpecializationID { get; set; }
    }
}
