namespace HCMBLL.Enums
{
    public enum BusinessSubCategoriesEnum
    {
        Delegations = 1,
        OverTimes = 2,
        PassengerOrders = 3,
        Assignings = 4,
        Lenders = 5,
        Scholarships = 6,
        Transfers = 7,
        GovernmentFunds = 8,
        EmployeesAllowances = 9,
        InternshipScholarships = 10,
        Vacations = 11,
        HolidaySettings = 12,
        SportsSeasons = 13,
        EndOfServices = 14,
        QualificationsDegrees = 15,
        Qualifications = 16,
        GeneralSpecializations = 17,
        VacationsByEndOfService = 18,
        EmployeeCareerHistoryByEndOfService = 19,
        EmployeesQualifications = 20,
        EmployeesExperiences = 21,
        GovernmentFundsDeactivation = 22,
        StopWork = 23,
        SickVacationsPaidAmount = 24,
        ChangeLogs = 25,
        Teachers = 26,
        InsteadDeportations = 27,
        OrganizationStructure = 28,
        ForgottenPassword = 29,
        ContractorsBasicSalaries = 30,
        AuthorizedPersonDecisionForEVacationRequest = 31,
        EmployeesExperiencesDetails = 32,
        EServicesProxies = 33,
    }
}