//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace HCMBLL.Enums
{
    //[Serializable]
    public enum EmployeesTypesEnum
    {
        //Def=0,
        //[EnumMemberAttribute]
        Civil=1,
        //[EnumMemberAttribute]
        Militry = 2,
    }
}