//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL.Enums
{
    public enum RanksCategoriesEnum
    {
        Employee = 1,
        User = 2,
        SaudiLabor = 3,
        ContractualSaudis = 4,
        ContractualExpats = 5,
        Army = 6
    }
}