//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL.Enums
{
    public enum StopWorkValidationEnum
    {
        Done = 1,
        RejectedBecauseAlreadyExist,
        RejectedBecauseOfConflictWithDelegation,
        RejectedBecauseOfConflictWithOverTime,
        RejectedBecauseOfConflictWithVacation,
        RejectedBecauseOfConflictWithInternshipScholarship,
        RejectedBecauseOfEndDateShouldBeMoreThanStartDate,
        RejectedBecauseOfThereIsAnotherStopWorkNotEnding

    }
}
