//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL.Enums
{
    public enum VacationsTypesEnum
    {
        Normal = 1,
        Exceptional = 2,
        Compulsory = 3,
        Sick = 4,
        Sports = 5,
        Born = 6,
        Dead = 7,
        AccompanimentSick = 8,
        Birth = 9,
        MotherHood = 10,
        Studies = 11,
        Compensatory = 12,
        Accompaniment = 13,
        Emergency = 14,
        Marriage=15,
        Exam=16
    }
}
