using HCMBLL.Enums;
using HCMDAL;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HCMBLL
{
    public class PromotionsRecordsLogsBLL : CommonEntity, IEntity
    {
        public int PromotionRecordLogID { get; set; }

        public PromotionsRecordsBLL PromotionRecord { get; set; }

        public int PromotionRecordNo { get; set; }

        public string ActionDescription { get; set; }

        public PromotionsRecordsActionsTypesBLL PromotionRecordActionType { get; set; }     

        public EmployeesCodesBLL ActionBy { get; set; }

        public DateTime ActionDate { get; set; }

        public virtual Result Add()
        {
            Result result = new Result();
            PromotionsRecordsLogs PromotionRecordLog = new PromotionsRecordsLogs();

            PromotionRecordLog.PromotionRecordID = this.PromotionRecord.PromotionRecordID;
            PromotionRecordLog.PromotionRecordNo = this.PromotionRecordNo.ToString();
            PromotionRecordLog.ActionDescription = this.ActionDescription;
            PromotionRecordLog.PromotionRecordActionTypeID = this.PromotionRecordActionType.PromotionActionTypeID;
            PromotionRecordLog.ActionDate = DateTime.Now;
            PromotionRecordLog.ActionBy = this.LoginIdentity.EmployeeCodeID;

            this.PromotionRecordLogID = new PromotionsRecordsLogsDAL().Insert(PromotionRecordLog);

            if (this.PromotionRecordLogID != 0)
            {
                result.Entity = this;
                result.EnumType = typeof(PromotionsRecordsValidationEnum);
                result.EnumMember = PromotionsRecordsValidationEnum.Done.ToString();
            }

            return result;
        }

        public List<PromotionsRecordsLogsBLL> GetByPromotionRecordID(int PromotionRecordID, out int totalRecordsOut, out int recFilterOut)
        {
            List<PromotionsRecordsLogs> PromotionsRecordsLogsList = new PromotionsRecordsLogsDAL(){
                    search = Search,
                    order = Order,
                    orderDir = OrderDir,
                    startRec = StartRec,
                    pageSize = PageSize
            }.GetByPromotionRecordID(PromotionRecordID, out totalRecordsOut, out recFilterOut);
            List<PromotionsRecordsLogsBLL> PromotionsRecordsLogsBLLList = new List<PromotionsRecordsLogsBLL>();
            if (PromotionsRecordsLogsList.Count > 0)
            {
                foreach (var item in PromotionsRecordsLogsList)
                    PromotionsRecordsLogsBLLList.Add(MapPromotionRecordLog(item));
            }

            return PromotionsRecordsLogsBLLList;
        }
        
        internal PromotionsRecordsLogsBLL MapPromotionRecordLog(PromotionsRecordsLogs item)
        {
            return item != null ?
                new PromotionsRecordsLogsBLL()
                    {
                        PromotionRecordLogID = item.PromotionRecordLogID,
                        ActionDescription = item.ActionDescription,
                        //PromotionRecord = new EmployeesCareersHistoryBLL().MapPromotionRecord(item.PromotionRecord),
                        PromotionRecordNo =Convert.ToInt32( item.PromotionRecordNo),
                        PromotionRecordActionType = new PromotionsRecordsActionsTypesBLL().MapPromotionActionType(item.PromotionsRecordsActionsTypes),
                        ActionDate = item.ActionDate,
                        ActionBy = new EmployeesCodesBLL().MapEmployeeCode(item.ActionByNav)
                    }
                : null;
        }
    
    }
}